[influx]
url   = "https://eu-central-1-1.aws.cloud2.influxdata.com"  # copy exact URL from InfluxDB Cloud
token = "-mwWR3pljKO9jn1d0esohbDxTGFtb54tp05xjcsaOiCWqX5VE43nGgAC2HZMHtAwYTvUq3OooEcAxX3_4h5Kxw=="             # read-only token for your bucket
org   = "1f23ebec0066b1e6"
bucket= "sheep_pred"

