[influx]
url   = "https://eu-central-1-1.aws.cloud2.influxdata.com"  # copy exact URL from InfluxDB Cloud
token = "z7lVjfDTo6oK4JmgvgQEIkVaBqdWPLhtGK7v3ljzIi-_xORIGeYrsgst_s80DyCC6miBlhsMqx7mmJz6CYzUIg=="             # read-only token for your bucket
org   = "1f23ebec0066b1e6"
bucket= "sheep_pred"
[openai]
api_key = "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"

