[influx]
url   = "https://eu-central-1-1.aws.cloud2.influxdata.com"  # copy exact URL from InfluxDB Cloud
token = "z7lVjfDTo6oK4JmgvgQEIkVaBqdWPLhtGK7v3ljzIi-_xORIGeYrsgst_s80DyCC6miBlhsMqx7mmJz6CYzUIg=="             # read-only token for your bucket
org   = "1f23ebec0066b1e6"
bucket= "sheep_pred"

