name: Predict behavior from Drive CSV and save back

on:
  workflow_dispatch:
    inputs:
      drive_folder_id:
        description: "Google Drive folder ID"
        required: true
        default: "1W-kmA5mwlnrheTKiAjVWh9xAEczk9wDg"
      csv_filename:
        description: "Optional: CSV filename in the folder (leave empty to use most recently modified CSV)"
        required: false
        default: ""
      model_path:
        description: "Path to the Keras .h5 model in the repo"
        required: true
        default: "sheepApp/model/ram_blstm_model.h5"
      class_labels:
        description: "Comma-separated labels (index order). If count mismatches model output, falls back to class_0.."
        required: false
        default: "grazing,ruminating,walking,other"

jobs:
  run-prediction:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "tensorflow-cpu>=2.13,<2.17" pandas numpy h5py \
            google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib tqdm

      # 🔐 Decode base64 secret -> sa.json and validate (no here-docs; YAML-safe)
      - name: Write & validate service account credentials
        shell: bash
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_B64 }}
        run: |
          if [ -z "${GOOGLE_SERVICE_ACCOUNT_JSON_B64}" ]; then
            echo "Secret GOOGLE_SERVICE_ACCOUNT_JSON_B64 is missing"; exit 1
          fi
          echo "${GOOGLE_SERVICE_ACCOUNT_JSON_B64}" | base64 --decode > sa.json
          python -c "import json,sys; json.load(open('sa.json')); print('sa.json is valid JSON.')"

      - name: Run prediction
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_B64 }}
          INPUT_DRIVE_FOLDER_ID: ${{ github.event.inputs.drive_folder_id }}
          INPUT_CSV_FILENAME: ${{ github.event.inputs.csv_filename }}
          INPUT_MODEL_PATH: ${{ github.event.inputs.model_path }}
          INPUT_CLASS_LABELS: ${{ github.event.inputs.class_labels }}
        run: python model/predict.py
